apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubearmor
  namespace: kube-system
  labels:
    daemonset: kubearmor
spec:
  selector:
    matchLabels:
      container: kubearmor
  template:
    metadata:
      labels:
        container: kubearmor
      annotations:
        container.apparmor.security.beta.kubernetes.io/kubearmor: unconfined
    spec:
      serviceAccountName: {{.Values.kubearmor.serviceAccountName }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostPID: true
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: kubearmor
        image: "{{ .Values.kubearmor.image.repository }}:{{ .Values.kubearmor.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        args: ["-gRPC=32767", "-logPath=/tmp/kubearmor.log", "-enableEnforcerPerPod"]
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.general.clusterName | quote }}
        ports:
        - containerPort: 32767
        volumeMounts:
          {{- toYaml .Values.kubearmor.volumeMounts | nindent 12 }}
          {{- if eq .Values.general.containerPlatform "docker" }}
            {{- toYaml .Values.kubearmor.volumeMountsDocker | nindent 12 }}
          {{- else if eq .Values.general.containerPlatform "containerd" }}
            {{- toYaml .Values.kubearmor.volumeMountsContainerd | nindent 12 }}
          {{- else if eq .Values.general.containerPlatform "microk8s" }}
            {{- toYaml .Values.kubearmor.volumeMountsContainerd | nindent 12 }}
          {{- else }}
            {{- toYaml .Values.kubearmor.volumeMountsDocker | nindent 12 }}
          {{- end }}
          {{- if .Values.general.gkeEnabled }}
            {{- toYaml .Values.kubearmor.volumeMountsGKE | nindent 12 }}
          {{- end }}
        livenessProbe:
          {{- toYaml .Values.kubearmor.livenessProbe | nindent 12 }}
        terminationMessagePolicy: File
        terminationMessagePath: /dev/termination-log
      terminationGracePeriodSeconds: 30
      volumes:
        {{- toYaml .Values.kubearmor.volumes | nindent 12 }}
        {{- if eq .Values.general.containerPlatform "docker" }}
          {{- toYaml .Values.kubearmor.volumesDocker | nindent 12 }}
        {{- else if eq .Values.general.containerPlatform "containerd" }}
          {{- toYaml .Values.kubearmor.volumesContainerd | nindent 12 }}
        {{- else if eq .Values.general.containerPlatform "microk8s" }}
          {{- toYaml .Values.kubearmor.volumesMicroK8s | nindent 12 }}
        {{- else }}
          {{- toYaml .Values.kubearmor.volumesDocker | nindent 12 }}
        {{- end }}
        {{- if .Values.general.gkeEnabled }}
          {{- toYaml .Values.kubearmor.volumesGKE | nindent 12 }}
        {{- end }}
