apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-kafka-client
  labels:
    kubearmor-app: kubearmor-kafka-client
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-kafka-client
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-kafka-client
    spec:
      containers:
      - name: kubearmor-kafka-client
        image: accuknox/kubearmor-kafka-client:latest
        env:
        - name: KUBEARMOR_SERVICE
          value: kubearmor.kube-system.svc:32767
        - name: KAFKA_BOOTSTRAP_SERVER
          value: kubearmor-kafka-cluster-kafka-bootstrap.kubearmor.svc:9092
        - name: TOPIC_MSG
          value: kubearmor-messages
        - name: TOPIC_ALERT
          value: kubearmor-alerts
        - name: TOPIC_LOG
          value: kubearmor-syslogs
