kubearmor:
  image:
    repository: gcr.io/accuknox/snapshot/kubearmor
    #repository: accuknox/kubearmor
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  name: kubearmor
  serviceAccountName: kubearmor
  volumes:
    - name: docker-sock-path # docker
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: usr-src-path # BPF
      hostPath:
        path: /usr/src
        type: Directory
    - name: lib-modules-path # BPF
      hostPath:
        path: /lib/modules
        type: Directory
    - name: sys-fs-bpf-path # BPF
      hostPath:
        path: /sys/fs/bpf
        type: Directory
    - name: sys-kernel-debug-path # BPF
      hostPath:
        path: /sys/kernel/debug
        type: Directory
    - name: etc-apparmor-d-path # AppArmor
      hostPath:
        path: /etc/apparmor.d
        type: Directory
    - name: var-log-audit-path # GKE-Auditd
      hostPath:
        path: /var/log/audit
        type: Directory
    - name: os-release-path # OS
      hostPath:
        path: /etc/os-release
        type: File
  volumeMounts:
    - name: docker-sock-path # docker (read-only)
      mountPath: /var/run/docker.sock
      readOnly: true
    - name: usr-src-path # BPF (read-only)
      mountPath: /usr/src
      readOnly: true
    - name: lib-modules-path # BPF (read-only)
      mountPath: /lib/modules
      readOnly: true
    - name: sys-fs-bpf-path # BPF (read-write)
      mountPath: /sys/fs/bpf
    - name: sys-kernel-debug-path # BPF (read-write)
      mountPath: /sys/kernel/debug
    - name: etc-apparmor-d-path # AppArmor (read-write)
      mountPath: /etc/apparmor.d
    - name: var-log-audit-path # GKE-Auditd (read-only)
      mountPath: /var/log/audit
      readOnly: true
    - name: os-release-path # OS (read-only)
      mountPath: /media/root/etc/os-release
      readOnly: true

  livenessProbe:
    exec:
      command:
      - /bin/bash
      - -c
      - |
        if [ -z $(pgrep kubearmor) ]; then
          exit 1;
        fi;
    initialDelaySeconds: 30
    periodSeconds: 10


cosauditd:
  image:
    repository: accuknox/kubearmor-cos-auditd
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  name: kubearmor
  serviceAccountName: kubearmor
  env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
  volumes:
    - name: host-path
      hostPath:
        path: /
        type: Directory
    - name: lib-systemd-path
      hostPath:
        path: /usr/lib64
        type: Directory
    - name: var-log-path
      hostPath:
        path: /var/log
        type: Directory
  volumeMounts:
    - name: lib-systemd-path
      mountPath: /host/lib
      readOnly: true
    - name: var-log-path
      mountPath: /var/log