apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-log-client
  labels:
    kubearmor-app: kubearmor-log-client
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-log-client
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-log-client
      annotations:
        kubearmor-policy: audited
    spec:
      containers:
      - name: kubearmor-log-client
        image: accuknox/kubearmor-log-client:latest
        args: ["-msgPath=stdout", "-logPath=stdout", "-logFilter=policy", "-json"]
        env:
        - name: KUBEARMOR_SERVICE
          value: kubearmor.kube-system.svc:32767
