name: ci-test-runtime

on:
  push:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-runtime.yml"
  pull_request:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-runtime.yml"

jobs:
  build:
    name: Test KubeArmor in Runtime
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Install the latest LLVM toolchain
        run: ./.github/workflows/install-llvm.sh

      - name: Compile libbpf
        run: ./.github/workflows/install-libbpf.sh

      - name: Setup a Kubernetes environment
        id: vars
        run: |
          echo "tag=latest" >> $GITHUB_OUTPUT
          RUNTIME=docker ./contribution/k3s/install_k3s.sh

      - name: Generate KubeArmor artifacts
        run: GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/build_kubearmor.sh ${{ steps.vars.outputs.tag }}

      - name: Run KubeArmor
        run: |
          sed -i 's/kubearmor\/kubearmor:latest/kubearmor\/kubearmor:${{ steps.vars.outputs.tag }}/g' ./KubeArmor/build/kubearmor-test-docker.yaml
          sed -i 's/kubearmor\/kubearmor-init:latest/kubearmor\/kubearmor-init:${{ steps.vars.outputs.tag }}/g' ./KubeArmor/build/kubearmor-test-docker.yaml
          kubectl apply -f deployments/CRD
          kubectl apply -f ./KubeArmor/build/kubearmor-test-docker.yaml
          kubectl wait --for=condition=ready --timeout=5m -n kube-system pod -l kubearmor-app=kubearmor
          kubectl get pods -A

      - name: Test KubeArmor using Ginkgo
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          make -C tests/
        timeout-minutes: 30

      - name: Capture KubeArmor logs
        if: ${{ failure() }}
        run: |
          kubectl -n kube-system describe pod $(kubectl get pods -n kube-system -l kubearmor-app=kubearmor --no-headers -o custom-columns=:metadata.name)
          kubectl exec -n kube-system daemonset/kubearmor -- cat /tmp/kubearmor.log > /tmp/kubearmor.log

      - name: Archive log artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: kubearmor.logs
          path: |
            /tmp/kubearmor.log

      - name: Check kubearmor log
        if: ${{ failure() }}
        run: cat /tmp/kubearmor.log
