on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'v*'

name: KubeArmor stable release update

jobs:
  build:
    name: Create KubeArmor Release - 18.04
    if: github.repository == 'kubearmor/kubearmor'
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout KubeArmor code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Pull Docker Hub image
        id: match
        run: |
            value=`cat STABLE-RELEASE`
            if [ ${{ github.ref }} == $value ]; then
              docker pull docker.io/kubearmor/kubearmor:$value
              docker image tag kubearmor/kubearmor:$value kubearmor/kubearmor:stable
              echo ::set-output name=tag::true
            else
              echo ::set-output name=tag::false
            fi

      - name: Login to Docker Hub
        if: steps.match.outputs.tag == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push KubeArmor images to Docker
        if: steps.match.outputs.tag == 'true'
        run: |
              ./KubeArmor/build/push_kubearmor.sh stable
